//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cat_estados")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub estado: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cat_codigos_postales::Entity")]
    CatCodigosPostales,
    #[sea_orm(has_many = "super::cat_localidades::Entity")]
    CatLocalidades,
    #[sea_orm(has_many = "super::cat_municipios::Entity")]
    CatMunicipios,
}

impl Related<super::cat_codigos_postales::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CatCodigosPostales.def()
    }
}

impl Related<super::cat_localidades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CatLocalidades.def()
    }
}

impl Related<super::cat_municipios::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CatMunicipios.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
