//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cat_municipios")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub municipio: String,
    pub id_estado: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cat_codigos_postales::Entity")]
    CatCodigosPostales,
    #[sea_orm(
        belongs_to = "super::cat_estados::Entity",
        from = "Column::IdEstado",
        to = "super::cat_estados::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CatEstados,
    #[sea_orm(has_many = "super::cat_localidades::Entity")]
    CatLocalidades,
}

impl Related<super::cat_codigos_postales::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CatCodigosPostales.def()
    }
}

impl Related<super::cat_estados::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CatEstados.def()
    }
}

impl Related<super::cat_localidades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CatLocalidades.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
