//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

pub use super::cat_codigos_postales::Entity as CatCodigosPostales;
pub use super::cat_estados::Entity as CatEstados;
pub use super::cat_localidades::Entity as CatLocalidades;
pub use super::cat_municipios::Entity as CatMunicipios;
